<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<?php echo $this->getChildHtml('amazonpayments_button_hint'); ?>
<div id="<?php echo $this->getWidgetHtmlId(); ?>" class="<?php echo $this->getWidgetClass(); ?> with-tooltip">
    <img src="<?php echo $this->getButtonWidgetUrl(); ?>" style="cursor:pointer;" />
    <?php if (!$this->getDisableOr()): ?>
        <span class="amazonpayments-or"><?php echo $this->__('-OR-'); ?></span>
    <?php endif; ?>
</div>
