<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="pay-with-amazon-onepage-shortcut">
    <h3><?php echo $this->__('Pay with Amazon'); ?></h3>
    <p><?php echo $this->getChildHtml('amazonpayments_onepage_button_tooltip'); ?></p>
    <div id="<?php echo $this->getWidgetHtmlId(); ?>" class="<?php echo $this->getWidgetClass(); ?>">
        <img src="<?php echo $this->getButtonWidgetUrl(); ?>"/>
    </div>
</div>
